export type AuthResponse = {
    auth: string,
    api: string,
    session_expire: string,
    update: string,
    add: string,
    clean: string,
    songs: number,
    albums: number,
    artists: number,
    genres: number,
    playlists: number,
    user: number,
    catalogs: number,
    videos: number,
    podcasts: number,
    podcast_episodes: number,
    shares: number,
    licenses: number,
    live_streams: number,
    labels: number,
}