export type AuthResponse = {
  add: string;
  albums: number;
  api: string;
  artists: number;
  auth: string;
  catalogs: number;
  compatible: string;
  clean: string;
  genres: number;
  labels: number;
  licenses: number;
  live_streams: number;
  playlists: number;
  podcasts: number;
  podcast_episodes: number;
  server: string;
  session_expire: string;
  shares: number;
  songs: number;
  update: string;
  user: number;
  version: string;
  videos: number;
};
